#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# GLOBAL VARIABLES

PROJ_PATH=${PWD}
PROJ_NAME=${PWD##*/}
REPO_PATH=$HOME/Dropbox/Development/Projects

enable_remote_dropbox=false

# -----------------------------------------------------------------------------
# FUNCTIONS

init_gitignore() {
    # Ignore Xcode releated files.
    echo "###############################################################################" >> .gitignore
    echo "# Xcode" >> .gitignore
    echo "" >> .gitignore
    echo "build/" >> .gitignore
    echo "*.pbxuser" >> .gitignore
    echo "!default.pbxuser" >> .gitignore
    echo "*.mode1v3" >> .gitignore
    echo "!default.mode1v3" >> .gitignore
    echo "*.mode2v3" >> .gitignore
    echo "!default.mode2v3" >> .gitignore
    echo "*.perspectivev3" >> .gitignore
    echo "!default.perspectivev3" >> .gitignore
    echo "xcuserdata" >> .gitignore
    echo "*.xccheckout" >> .gitignore
    echo "*.moved-aside" >> .gitignore
    echo "DerivedData" >> .gitignore
    echo "*.hmap" >> .gitignore
    echo "*.ipa" >> .gitignore
    echo "*.xcuserstate" >> .gitignore
    echo "$PROJ_NAME.xcworkspace/" >> .gitignore
    echo "*.playground/" >> .gitignore
    echo "" >> .gitignore
    
    # Ignore Xcode specific files.
    echo "###############################################################################" >> .gitignore
    echo "# OS X" >> .gitignore
    echo "" >> .gitignore
    echo ".DS_Store" >> .gitignore
    echo "" >> .gitignore
    
    # Ignore dependency manager checkout directories.
    echo "###############################################################################" >> .gitignore
    echo "# Dependency manager" >> .gitignore
    echo "" >> .gitignore
    echo "Pods/" >> .gitignore
    echo "Carthage/" >> .gitignore
    
    # Ignore assets.
    echo "###############################################################################" >> .gitignore
    echo "# Assets" >> .gitignore
    echo "" >> .gitignore
    echo "*.psd" >> .gitignore
    echo "*.sketch" >> .gitignore
}

init_dropbox() {
    if [ ! -d "$REPO_PATH" ]; then
        mkdir $REPO_PATH
    fi
    cd $REPO_PATH
    git init --bare $PROJ_NAME.git
    cd $PROJ_PATH
    git remote add dropbox $REPO_PATH/$PROJ_NAME.git
}

# -----------------------------------------------------------------------------
# SCRIPT

# Parse arguments.
while [[ $# > 1 ]]
do
    arg="$1"

    case $arg in
        -d|--dropbox)
        enable_remote_dropbox=true
        shift
        ;;

        *)
        ;;
    esac

    shift
done

echo ""
echo "Initializing git-flow..."
echo ""
if [ ! -d ".git" ]; then
    echo -e "[\033[31mFAIL\033[0m] No git repository found."
    echo ""
    exit 1
fi
git flow init
echo ""
echo -e "[\033[32mDONE\033[0m] Initialized git-flow."
echo ""

echo ""
echo "Creating .gitignore..."
echo ""
init_gitignore
git add .gitignore
git commit -am "Configured repository"
echo ""
echo -e "[\033[32mDONE\033[0m] Created .gitignore."
echo ""

if $enable_remote_dropbox ; then
    echo ""
    echo "Creating remote repository on Dropbox..."
    echo ""
    init_dropbox
    echo ""
    echo -e "[\033[32mDONE\033[0m] Created remote repository."
    echo ""
fi
