#!/usr/bin/env bash

###############################################################################
#                                                                             #
# x                                                                           #
#                                                                             #
# Scans the current folder for an Xcode workspace or project to open it.      #
#                                                                             #
###############################################################################

dirname="${PWD##*/}"
xcwork="${dirname}.xcworkspace"
xcproj="${dirname}.xcodeproj"
	
if [ -d "${xcwork}" ]; then
	open "${xcwork}"
elif [ -d "${xcproj}" ]; then
	open "${xcproj}"
else
	echo "ERROR: current directory doesn't contain any project."
fi
